import re

import bpy


class GenerateLODLevel(bpy.types.Operator):
    bl_idname = "object.mw_generate_lod_level"
    bl_options = {"REGISTER", "UNDO"}
    bl_label = "Generate LOD Level"
    bl_description = (
        "Add a new, lower-detail LOD level under this NiLODNode, generated by joining,"
        " decimating, and re-splitting (by material) a copy of the highest-detail level."
        " Every existing generated level is rebuilt from scratch to match the standard"
        " ratio/extent formula, and the newest level always gets the maximum draw distance"
        " (20000). The highest-detail (first) level is never touched"
    )

    # Distance (in Blender units) used by Merge by Distance to weld coincident
    # vertices along seams between joined source meshes before decimation.
    # Tune this if seams still show gaps/holes after welding.
    MERGE_DISTANCE = 0.0001

    @classmethod
    def poll(cls, context):
        ob = context.active_object
        return (ob is not None) and (ob.mw.block_type == "NiLODNode") and ob.children

    def execute(self, context):
        parent = context.active_object
        source = parent.children[0]

        # every child after the first is a previously generated level; they'll all be
        # rebuilt from `source` below so that ratio/extent always match the formula
        existing_levels = list(parent.children[1:])
        num_levels = len(existing_levels) + 1

        for level_ob in existing_levels:
            self.remove_hierarchy(level_ob)

        # The original highest-detail level is LOD0 and always ends at 1500.
        # Generated levels start at LOD1, so their extents continue from there.
        source.mw.lod_far_extent = 1500.0

        for level in range(num_levels):
            ratio = max(1-(0.2*(level+1)), 0.2*(0.75 ** (level-4)))
            is_last = level == (num_levels - 1)
            far_extent = 20000.0 if is_last else (level + 2) * 2500.0
            self.create_level(context, source, parent, level, ratio, far_extent)

        return {"FINISHED"}

    def create_level(self, context, source, parent, level, ratio, far_extent):
        # select the whole subtree so bpy.ops.object.duplicate() keeps it intact
        # (duplicated children are automatically re-parented onto their duplicated parents)
        bpy.ops.object.select_all(action="DESELECT")
        for o in (source, *self.iter_descendants(source)):
            o.select_set(True)
        context.view_layer.objects.active = source

        bpy.ops.object.duplicate(linked=False)
        duplicates = list(context.selected_objects)

        meshes = [o for o in duplicates if o.type == "MESH"]
        others = [o for o in duplicates if o.type != "MESH"]

        # The duplicated meshes are initially parented to duplicated wrapper empties.
        # Reparent them before removing those wrappers, otherwise deleting the wrappers
        # with do_unlink=True leaves the meshes as root objects instead of under the LOD node.
        for mesh in meshes:
            self.reparent_keep_transform(mesh, parent)

        # Any duplicated wrapper empties were only needed to keep the subtree intact
        # while duplicating; discard them now that the meshes stand on their own.
        for o in others:
            bpy.data.objects.remove(o, do_unlink=True)

        if not meshes:
            self.report({"WARNING"}, "No mesh data found under the selected object")
            return

        # join the duplicated meshes into one
        bpy.ops.object.select_all(action="DESELECT")
        for o in meshes:
            o.select_set(True)
        context.view_layer.objects.active = meshes[0]
        bpy.ops.object.join()
        joined = context.view_layer.objects.active

        # Weld coincident vertices along seams between the (formerly separate)
        # source meshes. Without this, the decimator treats each side of a seam
        # independently and can collapse them differently, opening up cracks/
        # holes where adjacent parts used to share edges implicitly.
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.mesh.remove_doubles(threshold=self.MERGE_DISTANCE)
        bpy.ops.object.mode_set(mode="OBJECT")

        # Count triangles before decimation for debugging.
        depsgraph = context.evaluated_depsgraph_get()
        joined_mesh = joined.evaluated_get(depsgraph).to_mesh()
        before_triangles = sum(
            len(poly.vertices) - 2
            for poly in joined_mesh.polygons
        )
        joined.evaluated_get(depsgraph).to_mesh_clear()

        # decimate
        modifier = joined.modifiers.new(name="Decimate", type="DECIMATE")
        modifier.ratio = ratio
        bpy.ops.object.modifier_apply(modifier=modifier.name)


        # Count triangles after decimation for debugging.
        depsgraph = context.evaluated_depsgraph_get()
        joined_mesh = joined.evaluated_get(depsgraph).to_mesh()
        after_triangles = sum(
            len(poly.vertices) - 2
            for poly in joined_mesh.polygons
        )
        joined.evaluated_get(depsgraph).to_mesh_clear()
        print(
            f"LOD level {level}: "
            f"ratio={ratio}, "
            f"triangles {before_triangles} -> {after_triangles}"
        )

        # separate by material
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.mesh.separate(type="MATERIAL")
        bpy.ops.object.mode_set(mode="OBJECT")

        pieces = list(context.selected_objects)
        name = self.level_name(source.name, level)

        if len(pieces) == 1:
            pieces[0].name = name
            pieces[0].mw.lod_far_extent = far_extent
            self.reparent_keep_transform(pieces[0], parent)
        else:
            container = bpy.data.objects.new(name, None)
            context.collection.objects.link(container)
            container.matrix_world = source.matrix_world
            container.mw.lod_far_extent = far_extent
            self.reparent_keep_transform(container, parent)

            for piece in pieces:
                self.reparent_keep_transform(piece, container)

    @staticmethod
    def remove_hierarchy(ob):
        for child in list(ob.children):
            GenerateLODLevel.remove_hierarchy(child)

        data = ob.data if ob.type == "MESH" else None
        bpy.data.objects.remove(ob, do_unlink=True)
        if data is not None and data.users == 0:
            bpy.data.meshes.remove(data)

    @staticmethod
    def iter_descendants(ob):
        for child in ob.children:
            yield child
            yield from GenerateLODLevel.iter_descendants(child)

    @staticmethod
    def reparent_keep_transform(ob, new_parent):
        world = ob.matrix_world.copy()
        ob.parent = new_parent
        ob.matrix_world = world

    @staticmethod
    def level_name(base_name, level):
        match = re.match(r"^(.*?)\d+$", base_name)
        prefix = match.group(1) if match else base_name
        return f"{prefix}{level + 1}"
