import re

import bmesh
import bpy


class GenerateLODLevel(bpy.types.Operator):
    bl_idname = "object.mw_generate_lod_level"
    bl_options = {"REGISTER", "UNDO"}
    bl_label = "Generate LOD Level"
    bl_description = (
        "Add a new, lower-detail LOD level under this NiLODNode, generated by joining,"
        " decimating, and re-splitting (by material) a copy of the highest-detail level."
        " Existing generated levels are left untouched except for their far draw distance,"
        " which is adjusted since the new level becomes the farthest. The highest-detail"
        " (first) level is never touched"
    )

    # Distance (in Blender units) used by Merge by Distance to weld coincident
    # vertices along seams between joined source meshes before decimation.
    # Tune this if seams still show gaps/holes after welding.
    MERGE_DISTANCE = 0.0001
    # Vertex group used internally to bias the Decimate modifier toward
    # protecting the vertices produced by the seam weld above (see
    # create_level()). Created fresh for each LOD level and removed again
    # once that level's decimation is applied.
    SEAM_VERTEX_GROUP_NAME = "mw_lod_seam"
    # Effective Decimate-modifier weight given to seam vertices: 0.0 leaves
    # them fully protected (their edges never collapse), 1.0 gives them no
    # special treatment at all and lets them decimate like any other vertex.
    # See the vertex group setup in create_level() for how this is applied.
    SEAM_VERTEX_WEIGHT = 0.1
    # A cell is 8192 units wide.
    LOD_STEP = 3500.0
    MAX_DIST = 3.4028235e38

    @classmethod
    def poll(cls, context):
        ob = context.active_object
        return (ob is not None) and (ob.mw.block_type == "NiLODNode") and ob.children

    def execute(self, context):
        parent = context.active_object
        source = parent.children[0]

        # every existing child after the first is a previously generated level.
        # Their geometry is kept as-is; only their far_extent may need to change,
        # since the new level we're about to add becomes the farthest one.
        existing_levels = list(parent.children[1:])
        new_level = len(existing_levels)  # 0-indexed, e.g. 0 for the first generated level

        source.mw.lod_far_extent = self.LOD_STEP

        for i, level_ob in enumerate(existing_levels):
            level_ob.mw.lod_far_extent = (i + 2) * self.LOD_STEP

        ratio = max(1 - (0.2 * (new_level + 1)), 0.2 * (0.75 ** (new_level - 4)))
        far_extent = self.MAX_DIST
        self.create_level(context, source, parent, new_level, ratio, far_extent)

        return {"FINISHED"}

    def create_level(self, context, source, parent, level, ratio, far_extent):
        # select the whole subtree so bpy.ops.object.duplicate() keeps it intact
        # (duplicated children are automatically re-parented onto their duplicated parents)
        bpy.ops.object.select_all(action="DESELECT")
        for o in (source, *self.iter_descendants(source)):
            o.select_set(True)
        context.view_layer.objects.active = source

        bpy.ops.object.duplicate(linked=False)
        duplicates = list(context.selected_objects)

        meshes = [o for o in duplicates if o.type == "MESH"]
        others = [o for o in duplicates if o.type != "MESH"]

        # The duplicated meshes are initially parented to duplicated wrapper empties.
        # Reparent them before removing those wrappers, otherwise deleting the wrappers
        # with do_unlink=True leaves the meshes as root objects instead of under the LOD node.
        for mesh in meshes:
            self.reparent_keep_transform(mesh, parent)

        # Any duplicated wrapper empties were only needed to keep the subtree intact
        # while duplicating; discard them now that the meshes stand on their own.
        for o in others:
            bpy.data.objects.remove(o, do_unlink=True)

        if not meshes:
            self.report({"WARNING"}, "No mesh data found under the selected object")
            return

        # join the duplicated meshes into one
        bpy.ops.object.select_all(action="DESELECT")
        for o in meshes:
            o.select_set(True)
        context.view_layer.objects.active = meshes[0]
        bpy.ops.object.join()
        joined = context.view_layer.objects.active

        # Weld coincident vertices along seams between the (formerly separate)
        # source meshes. Without this, the decimator treats each side of a seam
        # independently and can collapse them differently, opening up cracks/
        # holes where adjacent parts used to share edges implicitly.
        #
        # We do this with bmesh directly rather than bpy.ops.mesh.remove_doubles
        # so we can find out exactly *which* vertices the weld produced. Those
        # are the vertices now holding the seam together, and the decimator has
        # no idea that matters - left alone it can collapse them away again
        # like any other vertex, re-opening the cracks the weld just closed. We
        # record them here and bias the decimator to protect them, below.
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")

        bm = bmesh.from_edit_mesh(joined.data)
        bm.verts.ensure_lookup_table()
        weld_result = bmesh.ops.remove_doubles(
            bm, verts=list(bm.verts), dist=self.MERGE_DISTANCE
        )
        # Vertex indices go stale once verts are removed by the weld; refresh
        # them before reading .index below.
        bm.verts.index_update()
        # "targetmap" maps {vertex_removed: vertex_it_was_merged_into}; the
        # values are the survivors - the seam vertices we want to retain.
        if weld_result and "targetmap" in weld_result:
            merged_vert_indices = {v.index for v in set(weld_result["targetmap"].values())}
        else:
            merged_vert_indices = set()
        bmesh.update_edit_mesh(joined.data)

        # Source meshes are frequently authored/imported with inconsistent
        # winding order relative to one another (e.g. mirrored parts from a
        # NIF import). After joining, this leaves some faces flipped, which
        # by itself looks like "messed up normals" and also throws off the
        # decimator (it uses face normals to decide which edges to collapse).
        # Recalculate a globally consistent winding before decimating.
        bpy.ops.mesh.normals_make_consistent(inside=False)
        bpy.ops.object.mode_set(mode="OBJECT")

        # The Decimate modifier's edge-collapse algorithm does not correctly
        # interpolate custom split normals (the per-face-corner normals used
        # for hard edges / custom shading baked in on import). Trying to
        # preserve them through decimation is what produces the shading
        # artifacts on the simplified mesh. Instead, drop them here and
        # rebuild clean smoothing after decimating, below.
        bpy.ops.mesh.customdata_custom_splitnormals_clear()

        # Put the welded seam vertices in their own vertex group so the
        # Decimate modifier below can be biased to protect them.
        #
        # The Decimate modifier treats any vertex that is *not* a member of
        # its vertex group as having an implicit weight of 0.0, and a weight
        # of 0.0 on either endpoint makes that edge un-collapsible. Rather
        # than explicitly weighting every single vertex in the mesh, we take
        # advantage of that default: put only the (typically much smaller)
        # set of seam vertices into the group, then turn on the modifier's
        # "Invert Vertex Group" option so the meaning flips - seam vertices
        # (in the group) end up with SEAM_VERTEX_WEIGHT, and every other
        # vertex (not in the group, inverted from its implicit 0.0) ends up
        # with a full 1.0, decimating normally.
        seam_vgroup = joined.vertex_groups.new(name=self.SEAM_VERTEX_GROUP_NAME)
        if merged_vert_indices:
            seam_vgroup.add(
                list(merged_vert_indices), 1.0 - self.SEAM_VERTEX_WEIGHT, "REPLACE"
            )
        print(
            f"LOD level {level + 1}: "
            f"retaining {len(merged_vert_indices)} welded seam vertices through decimation"
        )

        # Count triangles before decimation for debugging.
        depsgraph = context.evaluated_depsgraph_get()
        joined_mesh = joined.evaluated_get(depsgraph).to_mesh()
        before_triangles = sum(
            len(poly.vertices) - 2
            for poly in joined_mesh.polygons
        )
        joined.evaluated_get(depsgraph).to_mesh_clear()

        # decimate
        modifier = joined.modifiers.new(name="Decimate", type="DECIMATE")
        modifier.ratio = ratio
        modifier.vertex_group = seam_vgroup.name
        modifier.invert_vertex_group = True
        bpy.ops.object.modifier_apply(modifier=modifier.name)

        # The vertex group above only existed to steer this decimation pass;
        # drop it now so it doesn't linger as leftover data on the LOD mesh.
        vgroup = joined.vertex_groups.get(self.SEAM_VERTEX_GROUP_NAME)
        if vgroup is not None:
            joined.vertex_groups.remove(vgroup)

        # The collapse operation above can leave a handful of degenerate/
        # flipped faces and always leaves flat per-face-loop normals (we
        # stripped the custom split normals before decimating, since the
        # modifier can't interpolate those correctly). Recalculate a
        # consistent, outward-facing normal per face, then let Blender
        # regenerate smooth vertex normals from that clean base.
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.mesh.normals_make_consistent(inside=False)
        bpy.ops.object.mode_set(mode="OBJECT")

        # Use angle-based auto smooth rather than a uniform shade_smooth().
        # We threw away the original custom split normals (the modifier can't
        # decimate those correctly), so this is what now decides which edges
        # read as "hard" vs "soft" on the simplified mesh. 60 degrees is
        # Blender's own default and gives a reasonable approximation of
        # where hard edges used to be, without needing the original data.
        # shade_auto_smooth() replaces the old use_auto_smooth/auto_smooth_angle
        # mesh properties (removed in Blender 4.1+): it shades smooth and adds
        # a "Smooth by Angle" modifier that splits normals past the given angle.
        bpy.ops.object.shade_auto_smooth(angle=1.0472)  # 60 degrees, in radians

        # Count triangles after decimation for debugging.
        depsgraph = context.evaluated_depsgraph_get()
        joined_mesh = joined.evaluated_get(depsgraph).to_mesh()
        after_triangles = sum(
            len(poly.vertices) - 2
            for poly in joined_mesh.polygons
        )
        joined.evaluated_get(depsgraph).to_mesh_clear()
        print(
            f"LOD level {level + 1}: "
            f"ratio={ratio}, "
            f"triangles {before_triangles} -> {after_triangles}"
        )

        # separate by material
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.mesh.separate(type="MATERIAL")
        bpy.ops.object.mode_set(mode="OBJECT")

        pieces = list(context.selected_objects)
        name = self.level_name(source.name, level)

        if len(pieces) == 1:
            pieces[0].name = name
            pieces[0].mw.lod_far_extent = far_extent
            self.reparent_keep_transform(pieces[0], parent)
        else:
            container = bpy.data.objects.new(name, None)
            context.collection.objects.link(container)
            container.matrix_world = source.matrix_world
            container.mw.lod_far_extent = far_extent
            self.reparent_keep_transform(container, parent)

            for piece in pieces:
                self.reparent_keep_transform(piece, container)

    @staticmethod
    def iter_descendants(ob):
        for child in ob.children:
            yield child
            yield from GenerateLODLevel.iter_descendants(child)

    @staticmethod
    def reparent_keep_transform(ob, new_parent):
        world = ob.matrix_world.copy()
        ob.parent = new_parent
        ob.matrix_world = world

    @staticmethod
    def level_name(base_name, level):
        match = re.match(r"^(.*?)\d+$", base_name)
        prefix = match.group(1) if match else base_name
        return f"{prefix}{level + 1}"
